### PR TITLE
tmux support 

### PR DESCRIPTION
**Pull request by thuanpham2311**
Issue: #7 

## Review

image
image
image
image
image

### CODE REVIEW

**Comment by mcchrish** [comment]
Hi @thuanpham2311 thanks for the PR! It looks great so far.

I guess I haven't documented this part well, but you have do make some extra steps to make the build script work. Please add the build script name into this line:

https://github.com/mcchrish/zenbones.nvim/blob/4c67a9e2a116cd4a693763d453a0fea7cc7a60ef/lua/zenbones/build.lua#L20

Then next is you have to run the build script by simply running `make`. Afterwards, just commit the generated tmux config.

**Review by mcchrish — CHANGES_REQUESTED** [review]
As mentioned above. Also please rebase the branch.

**Comment by thuanpham2311** [comment]
> uild script by simply running `make`. Afterwards, just commit the generated tmux config.

**i'm a noob**

image

**Comment by mcchrish** [comment]
That's strange. I can run the script properly and able to generate the tmux config.

What version of nvim are you using? Did you install `lush.nvim`?

**Comment by thuanpham2311** [comment]
> That's strange. I can run the script properly and able to generate the tmux config.
> 
> What version of nvim are you using? Did you install `lush.nvim`?

I use NVIM v0.5.0
I just install lush.nvim but still don't work

image

**Comment by mcchrish** [comment]
I see, can you temporarily remove the `-u NORC` option in the make file and try again?

**Comment by thuanpham2311** [comment]
> I see, can you temporarily remove the `-u NORC` option in the make file and try again?

**still not working**

image

**Comment by mcchrish** [comment]
Try this, open nvim, then run the command `:lua require("zenbones.build").build()`.
Make sure you are using your cloned copy:
```
Plug '~/path/to/your/cloned/zenbones.nvim'
```

**Comment by thuanpham2311** [comment]
> Try this, open nvim, then run the command `:lua require("zenbones.build").build()`.
> Make sure you are using your cloned copy:
> 
> ```
> Plug '~/path/to/your/cloned/zenbones.nvim'
> ``` 

**it worked :smile:**

image

**Comment by mcchrish** [comment]
Great, I probably need to update the makefile to be more portable.

Let me know if it's ready for review.

**Comment by thuanpham2311** [comment]
i'm stupid

**Pull request closed without merging**
